name: C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: g++ -std=c++20 *.cpp -o app

    - name: run
      run: ./app
