name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: g++ -std=c++20 C++Zaidimas.cpp -o app

    - name: Run
      run: ./app
